# Generated by Junie for Absence Alerts
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0036_rename_late_date_period_idx_school_atte_date_e50fa1_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("academic_year", models.CharField(max_length=20, unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "تسلسل تنبيهات الغياب",
                "verbose_name_plural": "تسلسلات تنبيهات الغياب",
            },
        ),
        migrations.CreateModel(
            name="AbsenceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("number", models.PositiveIntegerField()),
                ("academic_year", models.CharField(max_length=20)),
                ("class_name", models.CharField(max_length=50)),
                ("parent_name", models.CharField(blank=True, max_length=100)),
                ("parent_mobile", models.CharField(blank=True, max_length=30)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("excused_days", models.PositiveIntegerField(default=0)),
                ("unexcused_days", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("notified", "Notified"),
                            ("signed_student", "Signed Student"),
                            ("signed_parent", "Signed Parent"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("delivered_via", models.CharField(blank=True, max_length=20)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "signature_student",
                    models.ImageField(blank=True, null=True, upload_to="signatures/alerts/"),
                ),
                (
                    "signature_parent",
                    models.ImageField(blank=True, null=True, upload_to="signatures/alerts/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="school.student"),
                ),
                (
                    "wing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="school.wing",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبيه غياب",
                "verbose_name_plural": "تنبيهات غياب",
            },
        ),
        migrations.AddIndex(
            model_name="absencealert",
            index=models.Index(fields=["academic_year", "number"], name="absence_year_number_idx"),
        ),
        migrations.AddIndex(
            model_name="absencealert",
            index=models.Index(fields=["student"], name="absence_student_idx"),
        ),
        migrations.AddIndex(
            model_name="absencealert",
            index=models.Index(fields=["wing"], name="absence_wing_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="absencealert",
            unique_together={("academic_year", "number")},
        ),
    ]
