# Generated by Junie AI on 2025-10-31
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_absence_alerts"),
        ("school", "0027_remove_attendancerecord_att_day_between_1_7_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceEvidence",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="school.attendancerecord",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="attendance/evidence/%Y/%m/", verbose_name="ملف الإثبات"),
                ),
                ("content_type", models.CharField(max_length=100, blank=True, default="")),
                ("original_name", models.CharField(max_length=255, blank=True, default="")),
                ("note", models.CharField(max_length=300, blank=True, default="")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                        related_name="attendance_evidence_uploaded",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستند إثبات حضور",
                "verbose_name_plural": "مستندات إثبات الحضور",
                "indexes": [
                    models.Index(fields=["record", "uploaded_at"], name="evidence_rec_upl_idx"),
                ],
            },
        ),
    ]