# Generated by Django 5.2.7 on 2025-11-18 19:24

import apps.attendance.models_alerts
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_absence_alert_docx_archive"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="absencealert",
            new_name="attendance__academi_ba51e9_idx",
            old_name="absence_year_number_idx",
        ),
        migrations.RenameIndex(
            model_name="absencealert",
            new_name="attendance__student_876a21_idx",
            old_name="absence_student_idx",
        ),
        migrations.RenameIndex(
            model_name="absencealert",
            new_name="attendance__wing_id_55164d_idx",
            old_name="absence_wing_idx",
        ),
        migrations.RenameIndex(
            model_name="absencealertdocument",
            new_name="attendance__alert_i_c84039_idx",
            old_name="alert_docx_idx",
        ),
        migrations.AlterField(
            model_name="absencealertdocument",
            name="file",
            field=models.FileField(upload_to=apps.attendance.models_alerts._docx_upload_to),
        ),
        migrations.AlterField(
            model_name="attendanceevidence",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
