openapi: 3.0.3
info:
  title: Shahania School API
  version: 1.0.0
paths:
  /api/classes/:
    get:
      operationId: api_classes_list
      parameters:
      - name: ordering
        required: false
        in: query
        description: أي حقل يجب استخدامه عند ترتيب النتائج.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: رقم الصفحة ضمن النتائج المقسمة.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: مصطلح البحث.
        schema:
          type: string
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedClassList'
          description: ''
    post:
      operationId: api_classes_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Class'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Class'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Class'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Class'
          description: ''
  /api/classes/{id}/:
    get:
      operationId: api_classes_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا class.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Class'
          description: ''
    put:
      operationId: api_classes_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا class.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Class'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Class'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Class'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Class'
          description: ''
    patch:
      operationId: api_classes_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا class.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedClass'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedClass'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedClass'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Class'
          description: ''
    delete:
      operationId: api_classes_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا class.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/staff/:
    get:
      operationId: api_staff_list
      parameters:
      - name: ordering
        required: false
        in: query
        description: أي حقل يجب استخدامه عند ترتيب النتائج.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: رقم الصفحة ضمن النتائج المقسمة.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: مصطلح البحث.
        schema:
          type: string
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedStaffList'
          description: ''
    post:
      operationId: api_staff_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Staff'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Staff'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Staff'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Staff'
          description: ''
  /api/staff/{id}/:
    get:
      operationId: api_staff_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا staff.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Staff'
          description: ''
    put:
      operationId: api_staff_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا staff.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Staff'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Staff'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Staff'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Staff'
          description: ''
    patch:
      operationId: api_staff_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا staff.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedStaff'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedStaff'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedStaff'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Staff'
          description: ''
    delete:
      operationId: api_staff_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا staff.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/students/:
    get:
      operationId: api_students_list
      parameters:
      - name: ordering
        required: false
        in: query
        description: أي حقل يجب استخدامه عند ترتيب النتائج.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: رقم الصفحة ضمن النتائج المقسمة.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: مصطلح البحث.
        schema:
          type: string
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedStudentList'
          description: ''
    post:
      operationId: api_students_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Student'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
  /api/students/{id}/:
    get:
      operationId: api_students_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا student.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
    put:
      operationId: api_students_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا student.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Student'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
    patch:
      operationId: api_students_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا student.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedStudent'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedStudent'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedStudent'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
    delete:
      operationId: api_students_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: نوع رقم صحيح فريد يحدد هذا student.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Class:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        grade_level:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
      required:
      - grade_level
      - id
      - name
    PaginatedClassList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Class'
    PaginatedStaffList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Staff'
    PaginatedStudentList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Student'
    PatchedClass:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        grade_level:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
    PatchedStaff:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        staff_code:
          type: string
          maxLength: 30
        name:
          type: string
          maxLength: 120
        job_title:
          type: string
          maxLength: 120
        email:
          type: string
          format: email
          maxLength: 254
        phone:
          type: string
          maxLength: 30
    PatchedStudent:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        student_code:
          type: string
          maxLength: 30
        name:
          type: string
          maxLength: 120
        date_of_birth:
          type: string
          format: date
          nullable: true
        clazz:
          type: integer
          nullable: true
    Staff:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        staff_code:
          type: string
          maxLength: 30
        name:
          type: string
          maxLength: 120
        job_title:
          type: string
          maxLength: 120
        email:
          type: string
          format: email
          maxLength: 254
        phone:
          type: string
          maxLength: 30
      required:
      - id
      - name
      - staff_code
    Student:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        student_code:
          type: string
          maxLength: 30
        name:
          type: string
          maxLength: 120
        date_of_birth:
          type: string
          format: date
          nullable: true
        clazz:
          type: integer
          nullable: true
      required:
      - id
      - name
      - student_code
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
