name: sh_school_015

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: sh_school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${PG_HOST_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sh_school"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_buffers=256MB", "-c", "max_connections=200"]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    command: ["redis-server", "--appendonly", "no"]

volumes:
  pg_data:
    name: sh_school_pg_data
    external: true
