# Generated by Junie to add Subject and TeachingAssignment models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_staff_extra_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField("اسم المادة", max_length=150, unique=True),
                ),
                (
                    "code",
                    models.CharField(max_length=20, blank=True, null=True, unique=True),
                ),
                (
                    "weekly_default",
                    models.PositiveSmallIntegerField(null=True, blank=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name_ar"],
            },
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="school.staff",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="school.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="school.subject",
                    ),
                ),
                (
                    "no_classes_weekly",
                    models.PositiveSmallIntegerField("عدد الحصص أسبوعياً"),
                ),
                ("notes", models.CharField(max_length=200, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تكليف تدريس",
                "verbose_name_plural": "تكليفات التدريس",
                "unique_together": {("teacher", "classroom", "subject")},
                "indexes": [
                    models.Index(fields=["teacher"], name="teachassign_teacher_idx"),
                    models.Index(fields=["classroom"], name="teachassign_class_idx"),
                    models.Index(fields=["subject"], name="teachassign_subject_idx"),
                ],
            },
        ),
    ]
