# Generated by Junie to add ClassSubject through model and Class.subjects M2M
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_subject_and_teachingassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="school.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="school.subject",
                    ),
                ),
                (
                    "weekly_default",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        help_text="العدد الافتراضي للحصص أسبوعياً لهذه المادة في هذا الصف",
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة الصف",
                "verbose_name_plural": "مواد الصفوف",
                "unique_together": {("classroom", "subject")},
                "indexes": [
                    models.Index(fields=["classroom"], name="classsubject_class_idx"),
                    models.Index(fields=["subject"], name="classsubject_subject_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="class",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="classes",
                through="school.ClassSubject",
                to="school.subject",
            ),
        ),
    ]
