# Generated by Junie to add CalendarTemplate and CalendarSlot models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_classsubject_and_class_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "scope",
                    models.CharField(
                        max_length=50,
                        blank=True,
                        help_text="Upper, Ground, Secondary, Grade9(2-4)",
                    ),
                ),
                (
                    "days",
                    models.CharField(
                        max_length=50,
                        blank=True,
                        help_text="Comma-separated days (e.g., Sun,Mon,...) or 'ALL'",
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب اليوم الدراسي",
                "verbose_name_plural": "قوالب اليوم الدراسي",
                "indexes": [
                    models.Index(fields=["name"], name="caltmpl_name_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CalendarSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="school.calendartemplate",
                    ),
                ),
                (
                    "day",
                    models.CharField(max_length=10, help_text="Sun, Mon, Tue, Wed, Thu, ALL"),
                ),
                (
                    "period_index",
                    models.CharField(
                        max_length=16,
                        help_text="1..n or a label like BREAK/PRAYER/OTHER",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "block",
                    models.CharField(
                        max_length=10,
                        choices=(
                            ("class", "Class"),
                            ("break", "Break"),
                            ("prayer", "Prayer"),
                            ("other", "Other"),
                        ),
                        default="class",
                        help_text="نوع الكتلة",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "فترة زمنية",
                "verbose_name_plural": "فترات زمنية",
                "ordering": ["template", "day", "order", "start_time"],
                "indexes": [
                    models.Index(fields=["template"], name="calslot_template_idx"),
                    models.Index(fields=["day"], name="calslot_day_idx"),
                ],
                "unique_together": {("template", "day", "period_index")},
            },
        ),
    ]
