# Generated by Django 5.2.7 on 2025-10-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_timetable_entry"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="classsubject",
            new_name="school_clas_classro_1a6a75_idx",
            old_name="classsubject_class_idx",
        ),
        migrations.RenameIndex(
            model_name="classsubject",
            new_name="school_clas_subject_5421e4_idx",
            old_name="classsubject_subject_idx",
        ),
        migrations.RenameIndex(
            model_name="teachingassignment",
            new_name="school_teac_teacher_e1c1a0_idx",
            old_name="teachassign_teacher_idx",
        ),
        migrations.RenameIndex(
            model_name="teachingassignment",
            new_name="school_teac_classro_3ea4fb_idx",
            old_name="teachassign_class_idx",
        ),
        migrations.RenameIndex(
            model_name="teachingassignment",
            new_name="school_teac_subject_3b04e3_idx",
            old_name="teachassign_subject_idx",
        ),
    ]
