# Generated by Junie to drop TimetableEntry model as part of timetable reset
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "school",
            "0008_rename_classsubject_class_idx_school_clas_classro_1a6a75_idx_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimetableEntry",
        ),
    ]
