# Generated by Django 5.2.7 on 2025-10-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0017_fix_timestamps_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "أدمن"),
                    ("teacher", "معلم"),
                    ("school_principal", "مدير المدرسة"),
                    ("academic_vice", "النائب الاكاديمي"),
                    ("administrative_vice", "النائب الاداري"),
                    ("supervisor", "مشرف اداري"),
                    ("coordinator", "منسق"),
                    ("developer", "مطور"),
                    ("administrative", "إداري"),
                    ("staff", "موظف"),
                    ("psychologist", "اخصائي نفسي"),
                    ("store_keeper", "امين مخزن"),
                    ("social_specialist", "أخصائي اجتماعي"),
                    ("activities_specialist", "أخصائي أنشطة مدرسية"),
                    ("school_secretary", "سكرتير مدرسة"),
                    ("services_worker", "عامل خدمات"),
                    ("it_technician", "فني تقنية معلومات"),
                    ("accountant", "محاسب"),
                    ("lab_biology_prep", "محضر مختبر أحياء"),
                    ("lab_physics_prep", "محضر مختبر فيزياء"),
                    ("science_teacher", "مدرس علوم"),
                    ("support_assistant", "مرافق الدعم"),
                    ("academic_advisor", "مرشد أكاديمي"),
                    ("assistant_secretary", "مساعد سكرتير مدرسة"),
                    ("learning_resources_officer", "مسؤول مصادر التعلم"),
                    ("cafeteria_supervisor", "مشرف مقصف"),
                    ("student_observer", "ملاحظ طلبه"),
                    ("representative", "مندوب"),
                    ("receptionist", "موظف استقبال"),
                ],
                max_length=50,
            ),
        ),
    ]
