# Generated by Django 5.2.7 on 2025-10-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0019_merge_20251007_1718"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="class",
            name="class_students_count_nonneg",
        ),
        migrations.RemoveConstraint(
            model_name="staff",
            name="staff_email_ci_uniq",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="student_grade_section_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="student_email_lower_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="student_parent_email_lower_idx",
        ),
    ]
