# Generated by Django 5.2.7 on 2025-10-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0020_remove_class_class_students_count_nonneg_and_more"),
    ]

    operations = [
        # Drop TimetableEntry first (has FK to CalendarSlot)
        migrations.DeleteModel(
            name="TimetableEntry",
        ),
        # Then CalendarSlot (has FK to CalendarTemplate)
        migrations.DeleteModel(
            name="CalendarSlot",
        ),
        # Finally CalendarTemplate
        migrations.DeleteModel(
            name="CalendarTemplate",
        ),
    ]
