# Generated by Django 5.2.7 on 2025-10-11 13:33

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0021_remove_calendar_and_timetable_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("scope", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "verbose_name": "قالب يوم دراسي",
                "verbose_name_plural": "قوالب الأيام الدراسية",
            },
        ),
        migrations.CreateModel(
            name="SchoolHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start", models.DateField()),
                ("end", models.DateField()),
            ],
            options={
                "verbose_name": "عطلة مدرسية",
                "verbose_name_plural": "عطل مدرسية",
            },
        ),
        migrations.CreateModel(
            name="Wing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("floor", models.CharField(blank=True, max_length=20)),
                ("notes", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "جناح",
                "verbose_name_plural": "أجنحة",
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "سنة دراسية",
                "verbose_name_plural": "سنوات دراسية",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="one_current_year",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="school.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل دراسي",
                "verbose_name_plural": "فصول دراسية",
                "unique_together": {("academic_year", "name")},
            },
        ),
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("late_threshold_minutes", models.PositiveSmallIntegerField(default=5)),
                (
                    "late_to_equivalent_period_minutes",
                    models.PositiveSmallIntegerField(default=45),
                ),
                ("first_two_periods_numbers", models.JSONField(default=list)),
                (
                    "lesson_lock_after_minutes",
                    models.PositiveSmallIntegerField(default=120),
                ),
                ("daily_lock_time", models.TimeField(default=datetime.time(14, 30))),
                ("working_days", models.JSONField(default=list)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_policies",
                        to="school.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "سياسة الحضور",
                "verbose_name_plural": "سياسات الحضور",
            },
        ),
        migrations.CreateModel(
            name="AssessmentPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(default="general", max_length=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_packages",
                        to="school.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "باقة اختبارات",
                "verbose_name_plural": "باقات الاختبارات",
            },
        ),
        migrations.AddField(
            model_name="class",
            name="wing",
            field=models.ForeignKey(
                blank=True,
                help_text="الجناح الذي يتبع له هذا الصف",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="school.wing",
            ),
        ),
        migrations.CreateModel(
            name="TemplateSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("kind", models.CharField(default="lesson", max_length=20)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="school.periodtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقطع زمني",
                "verbose_name_plural": "مقاطع زمنية",
                "ordering": ["template", "start_time"],
                "unique_together": {("template", "number")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("period_number", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("late", "متأخر"),
                            ("absent", "غائب"),
                            ("runaway", "هروب"),
                            ("excused", "معذور"),
                            ("left_early", "انصراف مبكر"),
                        ],
                        max_length=20,
                    ),
                ),
                ("late_minutes", models.PositiveSmallIntegerField(default=0)),
                ("early_minutes", models.PositiveSmallIntegerField(default=0)),
                ("runaway_reason", models.CharField(blank=True, max_length=30)),
                ("excuse_type", models.CharField(blank=True, max_length=20)),
                ("excuse_note", models.CharField(blank=True, max_length=300)),
                ("source", models.CharField(default="teacher", max_length=20)),
                ("locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="school.class"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="school.student"),
                ),
                (
                    "subject",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="school.subject"),
                ),
                (
                    "teacher",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="school.staff"),
                ),
                (
                    "term",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="school.term"),
                ),
            ],
            options={
                "verbose_name": "سجل حضور حصة",
                "verbose_name_plural": "سجلات حضور الحصص",
                "indexes": [
                    models.Index(
                        fields=["student", "date"],
                        name="school_atte_student_0a3364_idx",
                    ),
                    models.Index(
                        fields=["classroom", "date"],
                        name="school_atte_classro_14d791_idx",
                    ),
                    models.Index(
                        fields=["teacher", "date"],
                        name="school_atte_teacher_e72fe8_idx",
                    ),
                    models.Index(fields=["status"], name="school_atte_status_e47666_idx"),
                ],
                "unique_together": {("student", "date", "period_number", "term")},
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("period_number", models.PositiveSmallIntegerField()),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable",
                        to="school.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="school.subject"),
                ),
                (
                    "teacher",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="school.staff"),
                ),
                (
                    "term",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="school.term"),
                ),
            ],
            options={
                "verbose_name": "حصة مجدولة",
                "verbose_name_plural": "حصص مجدولة",
                "indexes": [
                    models.Index(
                        fields=["classroom", "day_of_week", "period_number"],
                        name="school_time_classro_97e954_idx",
                    ),
                    models.Index(fields=["teacher"], name="school_time_teacher_21b74a_idx"),
                ],
                "unique_together": {("classroom", "day_of_week", "period_number", "term")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("present_periods", models.PositiveSmallIntegerField(default=0)),
                ("absent_periods", models.PositiveSmallIntegerField(default=0)),
                ("runaway_periods", models.PositiveSmallIntegerField(default=0)),
                ("excused_periods", models.PositiveSmallIntegerField(default=0)),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("early_minutes", models.PositiveIntegerField(default=0)),
                ("daily_absent_unexcused", models.BooleanField(default=False)),
                ("daily_excused", models.BooleanField(default=False)),
                ("daily_excused_partial", models.BooleanField(default=False)),
                ("locked", models.BooleanField(default=False)),
                (
                    "school_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="school.class"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="school.student"),
                ),
                (
                    "term",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="school.term"),
                ),
                (
                    "wing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.wing",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملخص حضور يومي",
                "verbose_name_plural": "ملخصات الحضور اليومية",
                "indexes": [
                    models.Index(fields=["date"], name="school_atte_date_966e39_idx"),
                    models.Index(fields=["school_class"], name="school_atte_school__8c9b80_idx"),
                    models.Index(fields=["wing"], name="school_atte_wing_id_2edb59_idx"),
                ],
                "unique_together": {("student", "date", "term")},
            },
        ),
    ]
