# Generated by Django 5.2.7 on 2025-10-13 19:25
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0022_periodtemplate_schoolholiday_wing_academicyear_term_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wing",
            name="supervisor",
            field=models.ForeignKey(
                to="school.staff",
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name="managed_wings",
                verbose_name="المشرف",
                help_text="المشرف المسؤول عن الجناح",
            ),
        ),
    ]
