# Generated by Django 5.2.7 on 2025-10-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0026_restore_db_best_practices"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attendancerecord",
            name="att_day_between_1_7",
        ),
        migrations.RemoveConstraint(
            model_name="attendancerecord",
            name="att_period_between_1_7",
        ),
        migrations.RemoveConstraint(
            model_name="term",
            name="one_current_term_per_year",
        ),
        migrations.RemoveConstraint(
            model_name="timetableentry",
            name="tt_day_between_1_5",
        ),
        migrations.RemoveConstraint(
            model_name="timetableentry",
            name="tt_period_between_1_7",
        ),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attrec_class_date_period_term_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attrec_student_date_term_idx",
        ),
        migrations.RemoveIndex(
            model_name="teachingassignment",
            name="ta_teacher_class_idx",
        ),
        migrations.RemoveIndex(
            model_name="timetableentry",
            name="tt_term_teacher_day_period_idx",
        ),
        migrations.RemoveIndex(
            model_name="timetableentry",
            name="tt_term_class_day_period_idx",
        ),
    ]
