# Generated by Django 5.2.7 on 2025-10-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0033_create_exitevent"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attendancerecord",
            name="att_day_between_1_7",
        ),
        migrations.RemoveConstraint(
            model_name="attendancerecord",
            name="att_period_between_1_7",
        ),
        migrations.RemoveConstraint(
            model_name="term",
            name="one_current_term_per_year",
        ),
        migrations.RemoveConstraint(
            model_name="timetableentry",
            name="tt_day_between_1_5",
        ),
        migrations.RemoveConstraint(
            model_name="timetableentry",
            name="tt_period_between_1_7",
        ),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attrec_class_date_period_term_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attrec_student_date_term_idx",
        ),
        migrations.RemoveIndex(
            model_name="teachingassignment",
            name="ta_teacher_class_idx",
        ),
        migrations.RemoveIndex(
            model_name="timetableentry",
            name="tt_term_teacher_day_period_idx",
        ),
        migrations.RemoveIndex(
            model_name="timetableentry",
            name="tt_term_class_day_period_idx",
        ),
        migrations.RenameIndex(
            model_name="exitevent",
            new_name="school_exit_student_0db503_idx",
            old_name="school_exit_student_date_idx",
        ),
        migrations.RenameIndex(
            model_name="exitevent",
            new_name="school_exit_reason_a3f575_idx",
            old_name="school_exit_reason_idx",
        ),
        migrations.RenameIndex(
            model_name="exitevent",
            new_name="school_exit_started_4bea78_idx",
            old_name="school_exit_started_at_idx",
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "حاضر"),
                    ("late", "متأخر"),
                    ("absent", "غائب"),
                    ("runaway", "هروب"),
                    ("excused", "إذن خروج"),
                    ("left_early", "انصراف مبكر"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exitevent",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["date", "status"], name="att_date_status_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["term", "student", "status"], name="att_term_student_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["teacher", "date", "period_number"],
                name="att_teacher_sched_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["classroom", "date", "period_number"],
                name="att_class_sched_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["date", "locked"], name="att_date_locked_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["student", "term"], name="att_student_term_idx"),
        ),
    ]
