# Generated by ChatGPT on 2025-10-22
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_add_enhanced_indexes_to_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('period_number', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('late_seconds', models.PositiveIntegerField()),
                ('late_mmss', models.CharField(max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_events', to='school.attendancerecord')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.staff')),
            ],
            options={
                'verbose_name': 'حدث تأخر',
                'verbose_name_plural': 'أحداث التأخر',
            },
        ),
        migrations.AddIndex(
            model_name='attendancelateevent',
            index=models.Index(fields=['date', 'period_number'], name='late_date_period_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelateevent',
            index=models.Index(fields=['student', 'date'], name='late_student_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelateevent',
            index=models.Index(fields=['classroom', 'date'], name='late_class_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelateevent',
            index=models.Index(fields=['teacher', 'date'], name='late_teacher_date_idx'),
        ),
    ]