# Generated by Django 5.2.7 on 2025-10-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0035_attendance_late_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="attendancelateevent",
            new_name="school_atte_date_e50fa1_idx",
            old_name="late_date_period_idx",
        ),
        migrations.RenameIndex(
            model_name="attendancelateevent",
            new_name="school_atte_student_6dce85_idx",
            old_name="late_student_date_idx",
        ),
        migrations.RenameIndex(
            model_name="attendancelateevent",
            new_name="school_atte_classro_a91e25_idx",
            old_name="late_class_date_idx",
        ),
        migrations.RenameIndex(
            model_name="attendancelateevent",
            new_name="school_atte_teacher_12b4a9_idx",
            old_name="late_teacher_date_idx",
        ),
        migrations.AlterField(
            model_name="attendancelateevent",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
