# Generated by Django 5.2.7 on 2025-11-15 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0025_grant_wing_supervisor_marri"),
        ("school", "0041_task_log"),
    ]

    operations = []
