# Generated by Django 5.2.7 on 2025-11-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0042_merge_0025_grant_wing_supervisor_marri_0041_task_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteLinks",
            fields=[],
            options={
                "verbose_name": "روابط المنصة",
                "verbose_name_plural": "روابط المنصة",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("school.class",),
        ),
        migrations.CreateModel(
            name="StudentLateSummary",
            fields=[],
            options={
                "verbose_name": "ملخص تأخيرات الطالب",
                "verbose_name_plural": "ملخصات تأخيرات الطلاب",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("school.student",),
        ),
        migrations.CreateModel(
            name="TimetableLinks",
            fields=[],
            options={
                "verbose_name": "روابط الجداول",
                "verbose_name_plural": "روابط الجداول",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("school.class",),
        ),
        migrations.RenameIndex(
            model_name="approvalrequest",
            new_name="school_appr_resourc_03a527_idx",
            old_name="school_appr_resource_idx",
        ),
        migrations.RenameIndex(
            model_name="approvalrequest",
            new_name="school_appr_status_6877b7_idx",
            old_name="school_appr_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="exitevent",
            new_name="school_exit_review__a12396_idx",
            old_name="school_exitevent_review_status_date_idx",
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="action",
            field=models.CharField(help_text="نوع المهمة/الفعل", max_length=50),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
