# Generated by Django 5.2.7 on 2025-11-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0043_sitelinks_studentlatesummary_timetablelinks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="excuse_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("medical", "طبي"),
                    ("official", "رسمي"),
                    ("family", "عائلي"),
                    ("transport", "مواصلات"),
                    ("other", "أخرى"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="runaway_reason",
            field=models.CharField(
                blank=True, choices=[("no_show", "لم يحضر"), ("left_and_not_returned", "خرج ولم يعد")], max_length=30
            ),
        ),
        migrations.CreateModel(
            name="AttendanceRecordArchive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("student_id", models.BigIntegerField(db_index=True)),
                ("classroom_id", models.BigIntegerField(db_index=True)),
                ("subject_id", models.BigIntegerField()),
                ("teacher_id", models.BigIntegerField(db_index=True)),
                ("term_id", models.BigIntegerField()),
                ("date", models.DateField(db_index=True)),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("period_number", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("status", models.CharField(max_length=20)),
                ("late_minutes", models.PositiveSmallIntegerField(default=0)),
                ("early_minutes", models.PositiveSmallIntegerField(default=0)),
                ("runaway_reason", models.CharField(blank=True, max_length=30)),
                ("excuse_type", models.CharField(blank=True, max_length=20)),
                ("excuse_note", models.CharField(blank=True, max_length=300)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("exit_reasons", models.CharField(blank=True, default="", max_length=200)),
                ("exit_left_at", models.DateTimeField(blank=True, null=True)),
                ("exit_returned_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="teacher", max_length=20)),
                ("locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("original_id", models.BigIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "أرشيف سجل حضور حصة",
                "verbose_name_plural": "أرشيف سجلات حضور الحصص",
                "indexes": [
                    models.Index(fields=["student_id", "date"], name="school_atte_student_b1873d_idx"),
                    models.Index(fields=["classroom_id", "date"], name="school_atte_classro_bbc030_idx"),
                    models.Index(fields=["teacher_id", "date"], name="school_atte_teacher_7a7034_idx"),
                    models.Index(fields=["date", "status"], name="school_atte_date_750dd8_idx"),
                    models.Index(fields=["term_id", "student_id", "status"], name="school_atte_term_id_5ba5b6_idx"),
                ],
            },
        ),
    ]
