# Generated by Junie (JetBrains) for initial discipline app schema
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Behavior Level",
                "verbose_name_plural": "Behavior Levels",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=16, unique=True)),
                ("category", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                ("default_actions", models.JSONField(default=list)),
                ("default_sanctions", models.JSONField(default=list)),
                ("severity", models.PositiveSmallIntegerField()),
                ("requires_committee", models.BooleanField(default=False)),
                (
                    "level",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="violations", to="discipline.behaviorlevel"),
                ),
            ],
            options={
                "verbose_name": "Violation",
                "verbose_name_plural": "Violations",
                "ordering": ("severity", "code"),
                "permissions": (("access", "Can access discipline module"),),
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("occurred_at", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=128)),
                ("narrative", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("under_review", "Under Review"), ("closed", "Closed")], default="open", max_length=16)),
                ("severity", models.PositiveSmallIntegerField()),
                ("committee_required", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("actions_applied", models.JSONField(blank=True, default=list)),
                ("sanctions_applied", models.JSONField(blank=True, default=list)),
                ("escalated_due_to_repeat", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="closed_incidents", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "reporter",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reported_incidents", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_incidents", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="school.student"),
                ),
                (
                    "violation",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="discipline.violation"),
                ),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
                "ordering": ("-occurred_at",),
            },
        ),
    ]