# Generated by Django 5.2.7 on 2025-11-15 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discipline", "0011_standing_committee_models"),
        ("discipline", "0012_grant_committee_view_mesyef"),
    ]

    operations = []
