# Generated by Django 5.2.7 on 2025-11-17 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discipline", "0015_incident_subject_fixation"),
        ("school", "0043_sitelinks_studentlatesummary_timetablelinks_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="behaviorlevel",
            options={"ordering": ("code",), "verbose_name": "مستوى السلوك", "verbose_name_plural": "مستويات السلوك"},
        ),
        migrations.AlterModelOptions(
            name="incident",
            options={
                "ordering": ("-occurred_at",),
                "permissions": (
                    ("incident_create", "Can create incident"),
                    ("incident_submit", "Can submit incident for review"),
                    ("incident_review", "Can review incident (approve/return)"),
                    ("incident_escalate", "Can escalate incident"),
                    ("incident_notify_guardian", "Can notify guardian for incident"),
                    ("incident_close", "Can close incident"),
                    ("incident_committee_view", "Can view incidents for committee workflow"),
                    ("incident_committee_schedule", "Can schedule/route incident to committee"),
                    ("incident_committee_decide", "Can record committee decision for incident"),
                ),
                "verbose_name": "واقعة",
                "verbose_name_plural": "وقائع",
            },
        ),
        migrations.AlterModelOptions(
            name="incidentauditlog",
            options={
                "ordering": ("-at", "-id"),
                "verbose_name": "سجل تدقيق الوقائع",
                "verbose_name_plural": "سجلات تدقيق الوقائع",
            },
        ),
        migrations.AlterModelOptions(
            name="incidentcommittee",
            options={"verbose_name": "لجنة الواقعة", "verbose_name_plural": "لجان الوقائع"},
        ),
        migrations.AlterModelOptions(
            name="standingcommittee",
            options={"verbose_name": "اللجنة السلوكية الدائمة", "verbose_name_plural": "اللجان السلوكية الدائمة"},
        ),
        migrations.AlterModelOptions(
            name="violation",
            options={
                "ordering": ("severity", "code"),
                "permissions": (("access", "Can access discipline module"),),
                "verbose_name": "مخالفة",
                "verbose_name_plural": "مخالفات",
            },
        ),
        migrations.AddField(
            model_name="violation",
            name="policy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="سياسة إجرائية مخصّصة للمخالفة: تكرارات/تصعيد/لجنة وإرشادات الإجراءات",
            ),
        ),
        migrations.AlterField(
            model_name="incidentattachment",
            name="kind",
            field=models.CharField(
                choices=[("pledge", "Pledge"), ("pledge_signed", "Pledge (Signed)"), ("other", "Other")],
                default="other",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="incidentauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("submit", "Submit"),
                    ("review", "Review"),
                    ("notify_guardian", "Notify Guardian"),
                    ("escalate", "Escalate"),
                    ("close", "Close"),
                    ("appeal", "Appeal"),
                    ("reopen", "Reopen"),
                    ("update", "Update"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="incidentcommittee",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="incidentcommitteemember",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="standingcommittee",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="standingcommitteemember",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("FULL_DAY", "Full Day"), ("PERIOD", "Period")], default="FULL_DAY", max_length=16
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="رقم الحصة عند اختيار نوع PERIOD", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UNEXCUSED", "Unexcused"), ("EXCUSED", "Excused")], default="UNEXCUSED", max_length=16
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ATTENDANCE_SYSTEM", "Attendance System"), ("MANUAL", "Manual")],
                        default="ATTENDANCE_SYSTEM",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="absences", to="school.student"
                    ),
                ),
            ],
            options={
                "verbose_name": "غياب",
                "verbose_name_plural": "غيابات",
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VERBAL_NOTICE", "Verbal Notice"),
                            ("WRITTEN_NOTICE", "Written Notice"),
                            ("WRITTEN_WARNING", "Written Warning"),
                            ("BEHAVIOR_CONTRACT", "Behavior Contract"),
                            ("GUARDIAN_MEETING", "Guardian Meeting"),
                            ("COUNSELING_SESSION", "Counseling Session"),
                            ("COMMITTEE_REFERRAL", "Committee Referral"),
                            ("SUSPENSION", "Suspension"),
                            ("RESTITUTION", "Restitution"),
                            ("EXTERNAL_NOTIFICATION", "External Notification"),
                            ("CONFISCATION_RECEIPT", "Confiscation Receipt"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("requires_guardian_signature", models.BooleanField(default=False)),
                ("doc_required", models.BooleanField(default=False)),
                ("doc_received_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="discipline.incident"
                    ),
                ),
            ],
            options={
                "verbose_name": "إجراء",
                "verbose_name_plural": "إجراءات",
                "ordering": ("-created_at",),
                "permissions": (
                    ("action_complete", "Can complete actions for incidents"),
                    ("action_create", "Can create actions for incidents"),
                    ("action_view", "Can view actions for incidents"),
                ),
            },
        ),
        migrations.CreateModel(
            name="ExcuseRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_JUSTIFICATION", "Pending Justification"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED_EXCUSE", "Approved"),
                            ("REJECTED_EXCUSE", "Rejected"),
                            ("NEEDS_CORRECTION", "Needs Correction"),
                        ],
                        default="PENDING_JUSTIFICATION",
                        max_length=24,
                    ),
                ),
                ("decision_reason", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("absences", models.ManyToManyField(related_name="excuse_requests", to="discipline.absence")),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_excuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_excuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب تبرير غياب",
                "verbose_name_plural": "طلبات تبرير الغياب",
                "ordering": ("-created_at",),
                "permissions": (
                    ("can_review_excuse_requests", "Can review absence excuse requests"),
                    ("can_convert_absence_status", "Can convert absences to excused"),
                    ("can_request_attachment_corrections", "Can request attachment corrections for excuses"),
                ),
            },
        ),
        migrations.CreateModel(
            name="ExcuseAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SUBMIT", "Submit"),
                            ("REVIEW", "Review"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("REQUEST_CORRECTION", "Request Correction"),
                            ("ATTACHMENT_ADD", "Attachment Add"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "excuse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="discipline.excuserequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق عذر",
                "verbose_name_plural": "سجلات تدقيق الأعذار",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ExcuseAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(choices=[("EXCUSE_DOC", "Excuse Document")], default="EXCUSE_DOC", max_length=16),
                ),
                ("url", models.CharField(max_length=512)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("origin", models.CharField(blank=True, help_text="scan/photo/other", max_length=16)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_excuse_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "excuse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="discipline.excuserequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرفق عذر",
                "verbose_name_plural": "مرفقات الأعذار",
            },
        ),
        migrations.AddIndex(
            model_name="absence",
            index=models.Index(fields=["student", "date"], name="abs_student_date_idx"),
        ),
        migrations.AddIndex(
            model_name="absence",
            index=models.Index(fields=["status"], name="abs_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="absence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "FULL_DAY"), ("period__isnull", True)),
                fields=("student", "date"),
                name="uniq_abs_full_day_per_student_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="absence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "PERIOD"), ("period__isnull", False)),
                fields=("student", "date", "period"),
                name="uniq_abs_period_per_student_date_period",
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["incident", "created_at"], name="act_inc_created_idx"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["type"], name="act_type_idx"),
        ),
        migrations.AddIndex(
            model_name="excuseauditlog",
            index=models.Index(fields=["excuse", "created_at"], name="excuse_audit_exc_dt_idx"),
        ),
        migrations.AddIndex(
            model_name="excuseauditlog",
            index=models.Index(fields=["action"], name="excuse_audit_action_idx"),
        ),
        migrations.AddIndex(
            model_name="excuseattachment",
            index=models.Index(fields=["excuse"], name="excuse_att_excuse_idx"),
        ),
        migrations.AddIndex(
            model_name="excuseattachment",
            index=models.Index(fields=["category"], name="excuse_att_category_idx"),
        ),
    ]
