# Generated by Django 5.2.7 on 2025-11-17 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discipline", "0016_alter_behaviorlevel_options_alter_incident_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentattachment",
            name="action",
            field=models.ForeignKey(
                blank=True,
                help_text="إن كان المرفق يخص إجراء محدد فسيُربط هنا",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="discipline.action",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentattachment",
            index=models.Index(fields=["action"], name="inc_att_action_idx"),
        ),
    ]
