# Generated by Django 5.2.7 on 2025-11-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discipline", "0019_excuse_request_due_at_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("under_review", "Under Review"),
                    ("closed", "Closed"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("review", "In Review"),
                    ("action_required", "Action Required"),
                    ("in_committee", "In Committee"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=16,
            ),
        ),
    ]
