name: Links Validator

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --max-redirects 5 README.md index.html "DOC/*.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}