name: Links Validator

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-links:
    name: check-links
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose --no-progress --max-redirects 10 --scheme https --timeout 20
            --exclude-mail
            --accept 200,204,403,429
            --retry-wait-time 2 --retry-count 3
            --exclude '(https?://(127\.0\.0\.1|localhost)(:\d+)?/.*|file://.*)'
            '**/*.md' '**/*.html'
          debug: false
          fail: true
          failIfEmpty: true
          format: markdown
          jobSummary: true
          lycheeVersion: v0.20.1
          output: lychee/out.md
          checkbox: true
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
