name: Python CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install black==24.* flake8
      - name: Black (check)
        run: black --check gen_index.py
      - name: Flake8
        run: flake8 gen_index.py --max-line-length=100
      - name: Generator check (no write)
        run: python gen_index.py --check