name: Quality Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality:
    name: Backend & Frontend Quality Gate
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports: ['5432:5432']
        env:
          POSTGRES_DB: sh_school
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json

      - name: Install system deps (Linux fonts/libs for potential PDF tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev libffi-dev libcairo2-dev fonts-noto-cjk

      - name: Run developer quality checks (PowerShell Core)
        shell: pwsh
        run: |
          ./scripts/quality_checks.ps1 -InstallOnly
          ./scripts/quality_checks.ps1

      - name: Upload audit logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: audit-artifacts
          path: |
            docs/audit/**/*
            frontend/.eslintcache
            **/pytest*.xml
          if-no-files-found: ignore