name: Quality Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  backend-and-frontend:
    name: Backend & Frontend Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install ruff mypy || true

      - name: Ruff (backend)
        run: ruff check --output-format=github || true

      - name: Mypy (backend)
        run: mypy || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Frontend install
        working-directory: frontend
        run: |
          if [ -f package.json ]; then npm ci || npm i; else echo "no frontend"; fi

      - name: Frontend lint
        if: ${{ hashFiles('frontend/package.json') != '' }}
        working-directory: frontend
        run: |
          if npm run | grep -q " lint"; then npm run lint || true; else echo "no lint script"; fi